In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('opt_output/optimization_log_test.csv')
df.head()

,MSE,scale_0,scale_1,scale_2,scale_3,scale_4,scale_5,scale_6,scale_7,scale_8,...,scale_2023,scale_2024,scale_2025,scale_2026,scale_2027,scale_2028,scale_2029,scale_2030,scale_2031,scale_2032
0,7.727818e+02,1.194029,1.243639,1.545904,1.158478,1.507564,0.501510,1.279662,0.720054,0.487736,...,0.174128,1.228620,0.762508,0.018687,1.934014,0.075810,1.429395,0.911111,0.607421,1.868598
1,3.635573e+07,1.570574,1.719222,1.468662,1.727629,0.944719,0.487940,0.736177,1.484601,0.621295,...,1.160056,1.439671,0.490359,0.751113,0.795145,0.755315,1.728240,1.740388,1.263023,0.934710
2,1.100033e+03,1.213593,1.892126,0.412587,1.599398,0.201016,0.544565,1.775072,1.504028,0.586883,...,1.418209,0.141684,0.278651,1.700611,0.568118,1.422989,1.861452,1.558208,0.714866,1.402172
3,8.636579e+03,1.346373,1.628728,0.825305,0.125598,1.957011,0.650293,1.790906,0.193468,0.154106,...,0.340162,1.516924,0.136307,0.641199,1.550508,0.803191,0.105544,1.409542,1.860169,0.919151
4,4.236605e+02,1.207239,0.807885,0.758273,0.345939,1.145169,1.392730,1.516803,0.757696,1.460057,...,1.776677,0.838069,0.608866,0.605737,1.020312,1.702567,1.612666,0.786327,0.648797,0.334868

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Columns: 2034 entries, MSE to scale_2032
dtypes: float64(2034)
memory usage: 842.3 KB

In [4]:
df.MSE.min()

80.72789870590726